### ISSUE TITLE
Error testing on MPII

### ISSUE THREAD

**Issue by Godatplay** [JimmySuen/integral-human-pose#15]
I'm trying to test on MPII with a custom config set to my data path and using the test.py found in integral_human_pose. I'm getting this error:
`'mpii_Dataset' is not defined`
because of course you're using mpii_hm36_Dataset. Is this just a bug/oversight? Or am I missing something? Changing my dataset name to that in the config does not work, and changing the import in test.py to import as mpii_Dataset also does not work, producing this error:
`TypeError: __init__() missing 1 required positional argument: 'label_config'`

How should I test on MPII?

**Comment by lck1201** [comment]
@Godatplay  Hi, the project is intended to test on HM3.6M of original version and eccv18 challenge.  We do not recommend to test on MPII, because we do not include related codes.  If you insist, you could write your own _mpii_Dataset_ function refering _hm36_Dataset_, and pass all necessary parameters when call it.

**Comment by Godatplay** [comment]
Good to know, thank you!

**Comment by Cherryliyin** [comment]
Stop wasting time. Integral loss does not work on MPII dataset at all. The actual effect is totally not as good as that described in the paper.
